---
- hosts: all
  gather_facts: false
  vars:
    # Vault Admin account
    vault_username: "administrator"
    vault_password: "Cyberark1"

    vault_ip: 192.168.57.4
    dr_ip: 192.168.57.3

    # PVWA Variables
    # Password of the local os admin
    local_admin_password: "CyberArk.123"
    # pvwa package name (name of downloaded zipfile WITHOUT extension)
    pvwa_installer_name: "Password Vault Web Access-Rls-v13.2.2"
    pvwa_installation_path: "C:\\CyberArk"
    # Path where source files will be copied to
    sources_path: C:\_sources
    # Path where source installer package will be from
    pvwa_zip_path: "../../src/installers/PVWA/{{pvwa_installer_name}}.zip"
    # Where password vault will be installled to
    pvwa_iis_app_folder: "C:\\inetpub\\wwwroot\\{{ pvwa_app_name }}"
    # Hostname for the URL
    pvwa_hostname: "pvwa.intern"
    chocolatey_packages:
      - sysinternals
      - notepadplusplus
      - powershell-core
      - bginfo
      - procexp
      - microsoft-edge
      - firefox # for foxy proxy
      - python # for mitm2swagger

  #     # Conjur Vault Synchronizer variables
  #     # Path relative to the role folder
  #     - vault_sync_zip_file_path: "../../src/installers/VaultConjurSynchronizer-Rls-v12.7.1.zip"
  #     - conjur_hostname: "conjur-cluster.adms.test"
  #     - sync_safe_name: "ConjurSync"
  #     - conjur_account_name: "adms"
  #     - conjur_lob_user: "LOBUser"
  #     - conjur_admin: "admin"
  #     - conjur_admin_password: "CyberArk!123"

  roles:
    # - name: ../roles/matiya.setup_windows_lab
    # - name: ../roles/matiya.pas_devtools
    - name: ../roles/matiya.pvwa
