# -*- mode: ruby -*-
#/usr/bin/env ruby

Vagrant.configure("2") do |config|

  # Box
  config.vm.box = "StefanScherer/windows_2019"

  # Setup a synced folder to the current path
  config.vm.synced_folder ".", "/vagrant", disabled: false
  # Take the users home and share it to the VM, in the path
  # C:\home\<home name>
  home = ENV['HOME'].gsub('\\', '/')
  config.vm.synced_folder home, home

  # Networking
  config.vm.hostname = "pvwa"
  config.vm.network "private_network", ip: "192.168.60.5"

  # Additional settings to make it more robust
  config.vm.guest = :windows
  config.winrm.port = 55985 # Make sure that this is correct
  config.winrm.max_tries = 20
  config.vm.boot_timeout = 600
  config.winrm.transport = :plaintext
  config.vm.communicator = "winrm"
  config.winrm.basic_auth_only = true
  config.winrm.timeout = 300
  config.vm.boot_timeout = 180
  config.winrm.retry_limit = 20
  config.windows.halt_timeout = 120

  # Export WINRM
  config.vm.network "forwarded_port", guest: 5985, host: 55985,id:"winrm",auto_correct: false
  config.vm.network "forwarded_port", guest: 5986, host: 56986,id:"winrms",auto_correct: false

  #Export RDP
  config.vm.network "forwarded_port", guest: 3389, host: 9385, id: "rdp", auto_correct: true
  # Export SSH
  config.vm.network "forwarded_port", guest: 22, host: 2225, id:"ssh", auto_correct: true
  # Export HTTPS
  config.vm.network "forwarded_port", guest: 443, host: 8443, id:"https", auto_correct: true

  # Customization
  config.vm.provider "virtualbox" do |v|
    v.name = "pvwa"
    v.gui = false
    v.memory = 2048
    v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"] # Enables drag-and-drop between host and guest
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--cpus", 2]
  end
  config.vm.provision "ansible" do |ansible|
    # ansible.verbose = "v"
    ansible.playbook = "setup_pvwa.yml"
    # Workaround for winrm_schem
    # See: https://github.com/hashicorp/vagrant/issues/10765
    ansible.host_vars = {
      "default" => { "ansible_winrm_scheme" => "http" }
    }
  end

end
