# -*- mode: ansible -*-

- hosts: all
  gather_facts: no
  vars_files:
    - ../../vars.yml
  vars:
    debug_playbook: true
  tasks:
    - name: Copy License, Operator and Master CDs.
      ansible.windows.win_copy:
        src: "{{item}}"
        dest: C:\_media
      with_items:
        - ../../src/vault/license
        - ../../src/vault/operator-cd
        - ../../src/vault/master-cd

    - name: Copy auxiliary scripts
      ansible.windows.win_copy:
        src: ../../src/scripts
        dest: C:\_media\

    - name: Copy Installers
      ansible.windows.win_copy:
        src: "{{item}}"
        dest: C:\_media\
      with_items:
        - "{{ vault_package }}"
        - "{{ client_package }}"

    - name: Unpack installers
      ansible.windows.win_powershell:
        chdir: C:\_media\
        script: |
          ls ".\Server-Rls-v{{pas_version}}.zip" | Expand-Archive
          # FIXME: CyberArk does not distribute a v13.0
          ls ".\Client-Rls-v12.6.zip" | Expand-Archive
        creates:
          - "{{vault_media}}"
          - "{{client_media}}"

    - name: Copy server silent installer configuration
      vars:
        - pvwa_upgrade: false
        - pvwa_enable_full_version: true
        - pvwa_enable_mobile_version: false
      ansible.windows.win_copy:
        content: "{{ lookup('ansible.builtin.template', '../../src/vault/config/setup_server.iss.j2') }}"
        dest: "{{ vault_media }}\\setup.iss"

    # - name: Copy server silent installer configuration
    #   ansible.windows.win_copy:
    #     src: ../../src/vault/config/setupv03.iss
    #     dest: "{{vault_media}}\\setup.iss"

    - name: Copy client silent installer configuration
      ansible.windows.win_copy:
        src: ../../src/vault/config/setup_client.iss
        dest: "{{client_media}}\\Client\\setup.iss"

    - name: Copy edited Hardening.ini file
      ansible.windows.win_copy:
        src: ../../src/vault/config/Hardening.ini
        dest: "{{vault_media}}\\Hardening\\Conf\\Hardening.ini"
